//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EM_CONNECT_LINE_FORCASE
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long ID { get; set; }
        public Nullable<long> SCRIPT_ID { get; set; }
        public Nullable<long> SCRIPT_CASE_ID { get; set; }
        public string FROM_DIV_ID { get; set; }
        public string FROM_POINT_ANCHORS { get; set; }
        public string TO_DIV_ID { get; set; }
        public string TO_POINT_ANCHORS { get; set; }
        public string CONTENT { get; set; }
    }
}
