//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EM_DB_SERVER
    {
        public EM_DB_SERVER()
        {
            this.EM_SCRIPT_NODE = new HashSet<EM_SCRIPT_NODE>();
            this.EM_SCRIPT_NODE_LOG = new HashSet<EM_SCRIPT_NODE_LOG>();
        }
    [Key]
        public long ID { get; set; }
        public string BYNAME { get; set; }
        public Nullable<long> DB_TAG_ID { get; set; }
        public string DB_TYPE { get; set; }
        public string IP { get; set; }
        public Nullable<int> PORT { get; set; }
        public string DATA_CASE { get; set; }
        public string USER { get; set; }
        public string PASSWORD { get; set; }
        public string REMARK { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public Nullable<long> CREATE_UID { get; set; }
        public Nullable<long> DELETE_UID { get; set; }
        public Nullable<System.DateTime> DELETE_TIME { get; set; }
        public short IS_DELETE { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<long> UPDATE_UID { get; set; }

        [ForeignKey("DB_TAG_ID")]
        public virtual EM_DB_TAG EM_DB_TAG { get; set; }
        public virtual ICollection<EM_SCRIPT_NODE> EM_SCRIPT_NODE { get; set; }
        public virtual ICollection<EM_SCRIPT_NODE_LOG> EM_SCRIPT_NODE_LOG { get; set; }
    }
}
