//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EM_HAND_RECORD
    {
        [Key]
        public long ID { get; set; }
        public Nullable<short> HAND_TYPE { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> OBJECT_ID { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public Nullable<short> IS_CANCEL { get; set; }
        public string CANCEL_REASON { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<long> OBJECT_CASE_ID { get; set; }
    }
}
