//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EM_ROLE_MODULE
    {
        [Key]
        public long ID { get; set; }
        public int ROLE_ID { get; set; }
        public long MODULE_ID { get; set; }
    
        public virtual EM_MODULE EM_MODULE { get; set; }
    }
}
