//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EM_SCRIPT_NODE_CASE_LOG
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long ID { get; set; }
        public Nullable<long> SCRIPT_NODE_CASE_ID { get; set; }
        public Nullable<System.DateTime> LOG_TIME { get; set; }
        public Nullable<short> LOG_LEVEL { get; set; }
        public string LOG_MSG { get; set; }
        public string SQL_MSG { get; set; }
    }
}
