//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EM_SCRIPT
    {
        public EM_SCRIPT()
        {
            this.EM_NODE_POSITION = new HashSet<EM_NODE_POSITION>();
            this.EM_SCRIPT_REF_NODE = new HashSet<EM_SCRIPT_REF_NODE>();
        }

        [Key]
        public long ID { get; set; }
        public string NAME { get; set; }
        public long SCRIPT_TYPE_ID { get; set; }
        public string CRON { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> RETRY_TIME { get; set; }
        public string REMARK { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public Nullable<long> CREATE_UID { get; set; }
        public Nullable<long> DELETE_UID { get; set; }
        public Nullable<System.DateTime> DELETE_TIME { get; set; }
        public short IS_DELETE { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<long> UPDATE_UID { get; set; }
    
        public virtual ICollection<EM_NODE_POSITION> EM_NODE_POSITION { get; set; }
        public virtual ICollection<EM_SCRIPT_REF_NODE> EM_SCRIPT_REF_NODE { get; set; }
        [ForeignKey("SCRIPT_TYPE_ID")]
        public virtual EM_SCRIPT_TYPE EM_SCRIPT_TYPE { get; set; }
    }
}
