//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EM_SCRIPT_NODE_TYPE
    {
        public EM_SCRIPT_NODE_TYPE()
        {
            this.EM_SCRIPT_NODE = new HashSet<EM_SCRIPT_NODE>();
            this.EM_SCRIPT_NODE_LOG = new HashSet<EM_SCRIPT_NODE_LOG>();
        }

        [Key]
        public long ID { get; set; }
        public string NAME { get; set; }
        public string REMARK { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public Nullable<long> CREATE_UID { get; set; }
        public Nullable<long> DELETE_UID { get; set; }
        public Nullable<System.DateTime> DELETE_TIME { get; set; }
        public short IS_DELETE { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<long> UPDATE_UID { get; set; }
    
        public virtual ICollection<EM_SCRIPT_NODE> EM_SCRIPT_NODE { get; set; }
        public virtual ICollection<EM_SCRIPT_NODE_LOG> EM_SCRIPT_NODE_LOG { get; set; }
    }
}
