//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EM_SCRIPT_NODE
    {
        [Key]
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<long> SCRIPT_NODE_TYPE_ID { get; set; }
        public string CODE { get; set; }
        public Nullable<long> DB_SERVER_ID { get; set; }
        public Nullable<short> SCRIPT_MODEL { get; set; }
        public string CONTENT { get; set; }
        public string REMARK { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public Nullable<long> CREATE_UID { get; set; }
        public Nullable<long> DELETE_UID { get; set; }
        public Nullable<System.DateTime> DELETE_TIME { get; set; }
        public short IS_DELETE { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<long> UPDATE_UID { get; set; }
        public string E_TABLE_NAME { get; set; }
        public string C_TABLE_NAME { get; set; }
        public Nullable<short> TABLE_TYPE { get; set; }
        public Nullable<short> TABLE_MODEL { get; set; }
    
        [ForeignKey("DB_SERVER_ID")]
        public virtual EM_DB_SERVER EM_DB_SERVER { get; set; }
        [ForeignKey("SCRIPT_NODE_TYPE_ID")]
        public virtual EM_SCRIPT_NODE_TYPE EM_SCRIPT_NODE_TYPE { get; set; }
    }
}
