//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EM_SCRIPT_NODE_FORCASE
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long ID { get; set; }
        public Nullable<long> SCRIPT_NODE_ID { get; set; }
        public Nullable<long> SCRIPT_NODE_TYPE_ID { get; set; }
        public Nullable<long> SCRIPT_CASE_ID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public Nullable<long> DB_SERVER_ID { get; set; }
        public Nullable<short> SCRIPT_MODEL { get; set; }
        public string CONTENT { get; set; }
        public string REMARK { get; set; }
        public string E_TABLE_NAME { get; set; }
        public string C_TABLE_NAME { get; set; }
        public Nullable<short> TABLE_TYPE { get; set; }
        public Nullable<short> TABLE_MODEL { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
