//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EM_SCRIPT_FUNCTION
    {
        [Key]
        public long ID { get; set; }
        public string NAME { get; set; }
        public string CONTENT { get; set; }
        public string REMARK { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<short> COMPILE_STATUS { get; set; }
    }
}
