//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyman.Service
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EM_SCRIPT_REF_NODE
    {
        [Key]
        public long ID { get; set; }
        public Nullable<long> SCRIPT_ID { get; set; }
        public Nullable<long> PARENT_NODE_ID { get; set; }
        public Nullable<long> CURR_NODE_ID { get; set; }
        public string REMARK { get; set; }
    
        [ForeignKey("SCRIPT_ID")]
        public virtual EM_SCRIPT EM_SCRIPT { get; set; }
    }
}
